# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Sitio web', 'Sitio web'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Google+', 'Google+'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Flickr', 'Flickr'), ('Pinterest', 'Pinterest'), ('Vimeo', 'Vimeo'), ('Otra', 'Otra')], max_length=25)),
                ('url', models.URLField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contrapartes.Contraparte')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
    ]
