# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_notas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
