# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20181018_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='tags',
            field=tagging.fields.TagField(blank=True, help_text='Separar elementos con "," ', max_length=255, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='notas',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='url video portada'),
        ),
    ]
