# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 16:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields
import tagging.fields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Aportes',
            },
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('nombre_audio', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=utils.get_file_path)),
                ('tags_aud', tagging.fields.TagField(blank=True, help_text='Separar elementos con "," ', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', ckeditor_uploader.fields.RichTextUploadingField()),
                ('aporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.Aportes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('nombre_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=utils.get_file_path, verbose_name='Adjunto')),
                ('tags_doc', tagging.fields.TagField(blank=True, help_text='Separar elementos con "," ', max_length=255, verbose_name='Tags')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Foros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('apertura', models.DateField(verbose_name='Apertura y recepci\xf3n de aportes')),
                ('cierre', models.DateField(verbose_name='Cierre de aportes')),
                ('fecha_skype', models.DateField(verbose_name='Propuesta de reuni\xf3n skype')),
                ('memoria', models.DateField(verbose_name='Propuesta entrega de memoria')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creacion'],
                'verbose_name_plural': 'Foros',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('nombre_img', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=utils.get_file_path, verbose_name='Foto')),
                ('tags_img', tagging.fields.TagField(blank=True, help_text='Separar elementos con "," ', max_length=255, verbose_name='Tags')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Im\xe1genes',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('nombre_video', models.CharField(blank=True, max_length=200, null=True)),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('tags_vid', tagging.fields.TagField(blank=True, help_text='Separar elementos con "," ', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='aportes',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.Foros'),
        ),
        migrations.AddField(
            model_name='aportes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
