# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agendas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fin'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio'),
        ),
    ]
